version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20  # Use a supported version (18 or 20)
    commands:
      - cd server  # Change to the server directory
      - npm install  # Install Node.js dependencies

  build:
    commands:
      - npm run build  # Or your build command for the server

cache:
  paths:
    - 'server/node_modules/**/*'  # Cache Node.js modules for faster builds
