version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd server
      - npm install

build:
  commands:
    - npm run start

cache:
  paths:
    - 'server/node_modules/**/*'
