version: 0.0
frontend:
  hooks:
    - BeforeInstall:
        - location: scripts/beforeInstall.sh
          timeout: 300
          runas: root
    - ApplicationStart:
        - location: scripts/applicationStart.sh
          timeout: 300
          runas: root
  files:
    - source: client/build
      destination: /var/www/frontend
